@startuml Data Analysis

    title       Data Analytics with LLM

    !define RectangleNode(x) class x << (R,#ADD1B2) >>
    !define DiamondNode(x) class x << (D,#ADD1B2) >>

    START: start
    dataset_detail : Get Dataset Details\n(Node)
    generate_sql_query : SQL query generator\n(Node)
    sanitize_sql_query : Sanitize SQL query\n(ConditionalNode)
    execute_sql_query : SQL query executer\n(Node)
    make_sql_decision : Check SQL error\n(Node)
    regenerate_sql_query : SQL query Re-generator.\n(Node)
    Python_Code_Generation : Python code generator\n(Node)
    sanitize_python_script : Python script sanitizer\n(ConditionalNode)
    Code_Execution : Python code executer\n(Node)
    Python_Code_Re_Generation : Python code re-generator\n(Node)
    Error_Handling : Check if there is is any error or not \n(Node)
    Report_Generation : Report generator\n(Node)
    END: End


    START --> dataset_detail: (dataset_name, query)
    dataset_detail --> generate_sql_query
    generate_sql_query --> sanitize_sql_query

    sanitize_sql_query --> execute_sql_query: if SQL query is safe
    sanitize_sql_query --> generate_sql_query: if SQL query is NOT safe
    sanitize_sql_query --> regenerate_sql_query: if SQL_error
    sanitize_sql_query --> END: if sanitize_check >= max_sanitize_check

    execute_sql_query --> make_sql_decision: To check SQL error
    make_sql_decision --> Python_Code_Generation: if NO SQL Error
    make_sql_decision --> regenerate_sql_query: if SQL error
    make_sql_decision --> END: if sql_generation_try >= max_sql_generation_try

    regenerate_sql_query --> sanitize_sql_query

    Python_Code_Generation --> sanitize_python_script

    sanitize_python_script--> Code_Execution: If Python code is safe to execute
    sanitize_python_script--> Python_Code_Re_Generation : If Python code is not safe to execute
    sanitize_python_script--> END: If Python_script_check >= max_Python_script_check

    Code_Execution --> Error_Handling 
    Error_Handling --> Report_Generation : If no error in Python code execution
    Error_Handling --> Python_Code_Re_Generation : If error in Python code execution
    Error_Handling --> END: if Python_script_check >= max_Python_script_check
    
    Python_Code_Re_Generation --> sanitize_python_script

    Report_Generation --> END

@enduml
